### ISSUE TITLE
Fibonacci solution bug

### ISSUE THREAD

**Issue by dragi-ns** [TheOdinProject/javascript-exercises#192]
Current fibonacci solution returns `1` instead of `0` when passed `"0"`, because it uses strict equality.

https://github.com/TheOdinProject/javascript-exercises/blob/8150be944bc01cb3bea5b50a760ae88e405693c1/fibonacci/fibonacci.js#L3

I'm opening this issue because tests state that the function should accept a string representation of a number.

**Comment by twalton83** [comment]
It's inferred that there probably should be some kind of type coercion here.

**Comment by HiddenOgre28** [comment]
Wouldn't a simple `count = parseInt(count, 10);` work here?

**Comment by Nitinbhojsingh** [comment]
I fixed this issue!

**Comment by KelvinMvungi** [comment]
No the issue is not fixed. I still find the solution for fibonacci exercise has `count === 0`. I just forked the repo a week ago.

**Comment by ManonLef** [comment]
@KelvinMvungi would you mind opening a new issue to explain what the issue is you’re having? That would make things easier to investigate and assign since the issues you’re commenting on are closed or very old it seems. You can reference these issue numbers or link to them in a new issue with your explanation and code example on how to reproduce the error you’re encountering

**Comment by KelvinMvungi** [comment]
@ManonLef I found the same exact issue which was solved a couple of weeks ago and the PR was merged but it did not appear in the repo. The repo had the same old problem but it's not a big deal, it's a simple issue.
